import { mkdir, writeFile } from "node:fs/promises";
import { deflateSync } from "node:zlib";

import { cursors } from "./cursor-bitmaps";

// Run with `bun scripts/build-cursors.ts`; no canvas dependency or browser runtime.
const scale = 2;
const size = 16 * scale;
const colors: Record<string, readonly [number, number, number, number]> = {
  ".": [0, 0, 0, 0],
  o: [238, 234, 227, 255],
  x: [30, 30, 30, 255],
  p: [243, 134, 161, 255],
};
const accents: Record<string, readonly [number, number, number, number]> = {
  pink: [243, 134, 161, 255],
  blue: [171, 186, 185, 255],
  sand: [216, 199, 164, 255],
  sage: [184, 195, 169, 255],
};
const crcTable = new Uint32Array(256);
for (let i = 0; i < 256; i++) {
  let value = i;
  for (let bit = 0; bit < 8; bit++) value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  crcTable[i] = value;
}
function chunk(name: string, data: Buffer): Buffer {
  const result = Buffer.alloc(data.length + 12);
  result.writeUInt32BE(data.length, 0);
  result.write(name, 4, "ascii");
  data.copy(result, 8);
  let crc = 0xffffffff;
  for (let i = 4; i < result.length - 4; i++) crc = crcTable[(crc ^ result[i]) & 255] ^ (crc >>> 8);
  result.writeUInt32BE((crc ^ 0xffffffff) >>> 0, result.length - 4);
  return result;
}
const header = Buffer.alloc(13);
header.writeUInt32BE(size, 0);
header.writeUInt32BE(size, 4);
header[8] = 8;
header[9] = 6;
const directory = new URL("../public/cursors/", import.meta.url);
await mkdir(directory, { recursive: true });
const rules: string[] = [];
for (const [accent, rgba] of Object.entries(accents)) {
  colors.p = rgba;
  const variables: string[] = [];
  for (const [name, cursor] of Object.entries(cursors)) {
    const raw = Buffer.alloc(size * (size * 4 + 1));
    for (let y = 0; y < size; y++)
      for (let x = 0; x < size; x++) {
        const pixel = cursor.bitmap[Math.floor(y / scale)][Math.floor(x / scale)];
        raw.set(colors[pixel], y * (size * 4 + 1) + 1 + x * 4);
      }
    const png = Buffer.concat([
      Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
      chunk("IHDR", header),
      chunk("IDAT", deflateSync(raw, { level: 9 })),
      chunk("IEND", Buffer.alloc(0)),
    ]);
    const filename = accent === "pink" ? `${name}.png` : `${accent}-${name}.png`;
    await writeFile(new URL(filename, directory), png);
    variables.push(
      `    --cur-${name}: url('/cursors/${filename}') ${cursor.hotspot[0] * scale} ${cursor.hotspot[1] * scale}, ${cursor.fallback};`,
    );
  }
  rules.push(
    `  ${accent === "pink" ? ":root" : `:root[data-cursor-accent='${accent}']`} {\n${variables.join("\n")}\n  }`,
  );
}
const systemVariables = Object.entries(cursors).map(
  ([name, cursor]) => `    --cur-${name}: ${cursor.fallback};`,
);
const css = `/* Generated by bun scripts/build-cursors.ts from the reference 16×16 bitmaps. */
@media (pointer: fine) {
${rules.join("\n\n")}

  :root[data-pref-cursors='false'] {
${systemVariables.join("\n")}
  }

  :root {
    cursor: var(--cur-default, default);
  }

  :where(a, button, summary, select, [role='button'], input[type='submit'], input[type='button']) {
    cursor: var(--cur-pointer, pointer);
  }

  :where(p, textarea, input:not([type='submit']):not([type='button']), [contenteditable='true']) {
    cursor: var(--cur-text, text);
  }

  :where(.board-card, [data-draggable='true']) {
    cursor: var(--cur-grab, grab);
  }

  :where(.board-card.is-dragging, [data-dragging='true']) {
    cursor: var(--cur-grabbing, grabbing);
  }

  :where(.para-anchor, [data-paragraph-anchor]) {
    cursor: var(--cur-anchor, crosshair);
  }

  :where([disabled], [aria-disabled='true']) {
    cursor: var(--cur-not-allowed, not-allowed);
  }

  html.is-leaving,
  html.is-leaving * {
    cursor: var(--cur-progress, progress) !important;
  }
}
`;
await writeFile(new URL("../src/styles/cursors.css", import.meta.url), css);
console.log(
  `Generated ${Object.keys(cursors).length * Object.keys(accents).length} ${size}×${size} cursor PNGs and cursor CSS.`,
);
